---
title: "ML"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# data prep; 1 year survival
```{r}
mtx = read.csv("~/documents/Segundo_Melanoma/Results/ML/1-yr-survival_phospho.csv", row.names=1)
colnames(mtx)[length(colnames(mtx))] = "label"
smp_size <- floor(0.7 * nrow(mtx))
index <- sample(seq_len(nrow(mtx)),size=smp_size)
train <- mtx[index, ]
test <- mtx[-index, ]

```

# LASSO
```{r}
library(lars)
library(glmnet)
library(caret)

cv.out =cv.glmnet(as.matrix(train[,1:(length(colnames(mtx))-1)]), as.matrix(train$label),alpha =1,nfolds=10)
plot(cv.out)
cv.out$lambda.min
```

```{r}
# Fitting
model =glmnet(as.matrix(train[,1:(length(colnames(mtx))-1)]),as.matrix(train$label),alpha=1,lambda=c(cv.out$lambda.min))
# Predict results
results_prob <- predict(model, as.matrix(subset(test,select=c(1:(length(colnames(mtx))-1)))),type='response')
# Actual answers
answers <- factor(test$label, levels=c(0,1))
results <- round(results_prob)
results <- factor(results, levels=c(0,1))
# Accuracy calculation
misClasificError <- mean(answers != results)
# Collecting results
acc <- 1-misClasificError
# Confusion matrix
cm <- confusionMatrix(data=results, reference=answers)
fpr <- cm$table[2]/nrow(test)
fnr <- cm$table[3]/nrow(test)
# Average accuracy of the model
print('accuracy:')
acc
# Confusion matrix and plots of fpr and fnr
print('fpr:')
fpr
print('fnr:')
fnr
print('Last miss classification error:')
misClasificError
```

confusion matrix of LASSO prediction
```{r}
print(cm)
```

variable importance
```{r}
print(coef(model))
```

## CART

```{r}
library(rpart)
library(rpart.plot)
library(caret)

binary.model <- rpart(label ~ ., data=train,cp=0.02, method='class')
rpart.plot(binary.model, digit = 3, fallen.leaves = T, varlen=0, type = 3, extra = 106,
main="Response")

```

```{r}
# Predict results
results_prob <- predict(binary.model, test[,1:(length(colnames(mtx))-1)], type='class')
# Actual answers
answers <- factor(test$label, levels=c(0,1))
results <- factor(results_prob, levels=c(0,1))
# Accuracy calculation
misClasificError <- mean(answers != results)
# Collecting results
acc <- 1-misClasificError
# Confusion matrix
cm <- confusionMatrix(data=results, reference=answers)
fpr <- cm$table[2]/nrow(test)
fnr <- cm$table[3]/nrow(test)
print('accuracy:')
acc
print('fpr:')
mean(fpr)
print('fnr:')
mean(fnr)
print('miss classification error:')
misClasificError
```

```{r}
print('confusion matrix:')
cm
print('variable importance:')
varImp(binary.model)
```

## Random Forests
```{r}
library(randomForest)
library(rpart.plot)
library(caret)

rf.model <- randomForest(label ~ ., data=train,mtry=4,importance=T)
# Predict results
results_prob <- predict(rf.model, newdata = test[,1:(length(colnames(mtx))-1)], type='class')
# Actual answers
answers <- factor(test$label, levels=c(0,1))
results <- round(results_prob)
results <- factor(results, levels=c(0,1))
# Accuracy calculation
misClasificError <- mean(answers != results)
# Collecting results
acc <- 1-misClasificError
# Confusion matrix
cm <- confusionMatrix(data=results, reference=answers)
fpr <- cm$table[2]/nrow(test)
fnr <- cm$table[3]/nrow(test)
print('accuracy:')
acc
print('fpr:')
mean(fpr)
print('fnr:')
mean(fnr)
print('miss classification error:')
misClasificError
```

```{r}
print('confusion matrix:')
cm
print('variable importance:')
varImp(rf.model)


```

### gradient tree boosting
```{r}
library(gbm)
library(rpart.plot)
library(caret)

gbm.model <- gbm(label ~ ., data=train,distribution = "gaussian", interaction.depth =4,n.trees =30000,shrinkage = 0.1,n.cores=2)
# Predict results
results_prob <- predict(gbm.model, newdata = test[,1:(length(colnames(mtx))-1)], type="response",n.trees =30000)

# Actual answers
answers <- factor(test$label, levels=c(0,1))
results <- round(results_prob)
results <- factor(results, levels=c(0,1))
# Accuracy calculation
misClasificError <- mean(answers != results)
# Collecting results
acc <- 1-misClasificError
# Confusion matrix
cm <- confusionMatrix(data=results, reference=answers)
fpr <- cm$table[2]/nrow(test)
fnr <- cm$table[3]/nrow(test)
print('accuracy:')
acc
print('fpr:')
mean(fpr)
print('fnr:')
mean(fnr)
print('miss classification error:')
misClasificError
```

```{r}
print('confusion matrix:')
cm
print('variable importance:')
summary(gbm.model)
```

### SVM
```{r}
library(e1071)
library(rpart.plot)
library(caret)

svm.model <- svm(label ~ ., data=train, type='C-classification', kernel='linear')
# Predict results
results_prob <- predict(svm.model, newdata = test[,1:(length(colnames(mtx))-1)], type="C-classification")
# Actual answers
answers <- factor(test$label, levels=c(0,1))

results <- factor(results_prob, levels=c(0,1))
# Accuracy calculation
misClasificError <- mean(answers != results)
# Collecting results
acc <- 1-misClasificError
# Confusion matrix
cm <- confusionMatrix(data=results, reference=answers)
fpr <- cm$table[2]/nrow(test)
fnr <- cm$table[3]/nrow(test)
print('accuracy:')
acc
print('fpr:')
mean(fpr)
print('fnr:')
mean(fnr)
print('miss classification error:')
misClasificError
```

```{r}
print('confusion matrix:')
cm
```

